[package]
name = "graph_example"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "5.5.3"
dhat = "0.3.3"
getopts = "0.2.21"
#itertools = "0.13.0"
petgraph = "0.6.5"
rayon = "1.10.0"

[profile.release]
debug = 1

[features]
dhat-heap = []    # if you are doing heap profiling

[[bin]]
name = "main"
path = "src/main.rs"
