[package]
name = "graph_example"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = {version = "6.0.1", features = ["rayon"]}
getopts = "0.2.21"
petgraph = { version = "0.6.5", features = ["rayon"] }
rayon = "1.10.0"
rustworkx-core = "0.15.1"

#io_util = {path = "src/graphmap_utils_par.rs"}
#graphmap_utils_par = {path = "src/graphmap_utils_par.rs"}
#graphmap_utils_rayon = {path = "src/graphmap_utils_rayon.rs"}

[[bin]]
name = "naive"
path = "src/naive.rs"

#par
[[bin]]
name = "par_main_base"
path = "src/par_main_base.rs"

[[bin]]
name = "par_main"
path = "src/par_main.rs"

[[bin]]
name = "par_main_opt"
path = "src/par_main_opt.rs"


#rayon
[[bin]]
name = "rayon_main_base"
path = "src/rayon_main_base.rs"

[[bin]]
name = "rayon_main"
path = "src/rayon_main.rs"

[[bin]]
name = "rayon_main_opt"
path = "src/rayon_main_opt.rs"
