[package]
name = "graph_example"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = {version = "6.0.1", features = ["rayon"]}
getopts = "0.2.21"
#itertools = "0.13.0"
petgraph = { version = "0.6.5", features = ["rayon"] }
rayon = "1.10.0"
#parking_lot = "0.12.3"

[[bin]]
name = "main_base"
path = "src/main_base.rs"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "main_opt"
path = "src/main_opt.rs"

[[bin]]
name = "native_thread"
path = "src/sketches/native_thread.rs"

#[[bin]]
#name = "big_graph_test"
#path = "src/big_graph_test.rs"