[package]
name = "graph_example"
version = "0.1.0"
edition = "2021"

[dependencies]
dashmap = "5.5.3"
petgraph = "0.6.5"
rayon = "1.10.0"

[[bin]]
name = "main"
path = "src/main.rs"


[[bin]]
name = "graphmap"
path = "src/graphmap.rs"

#[[bin]]
#name = "multithreaded_graph"
#path = "src/multithreaded_graph.rs"

#[[bin]]
#name = "singlethreaded_graph"
#path = "src/singlethreaded_graph.rs"

[[bin]]
name = "generalized_graph"
path = "src/generalized_graph.rs"

[[bin]]
name = "filtermap"
path = "src/filtermap.rs"

[[bin]]
name = "parallel_graph"
path = "src/parallel_graph.rs"


[[bin]]
name = "pruning_test"
path = "src/pruning_test.rs"

#[[bin]]
#name = "input_util"
#path = "src/input_util.rs"
